export const TAG_OPTIONS = [
  "Canadian",
  "CertClean",
  "Chemical Free",
  "Dairy Free",
  "EWG Verified",
  "EcoCert",
  "Fair Trade",
  "Gluten Free",
  "Hypoallergenic",
  "Natural",
  "No Talc",
  "Non-GMO",
  "Organic",
  "Peanut Free Product",
  "Sugar Free",
  "USDA Organic",
  "Vegan",
  "Alcohol Free",
  "Cruelty Free",
  "Oil Free",
  "Silicone Free",
  "Water Free",
];
